name: Justine
favicon: null
layout_spectrum: 0.24734
typography_spectrum: 0.74589
title: Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9eaee'
    - '#b9bdc6'
    - '#607499'
    - '#17270d'
    - '#374629'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
